[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', '../../../lib']
solc_version = '0.8.19'
remappings = [
    "test/=test/",
    "@openzeppelin/contracts=../../../node_modules/@openzeppelin/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config