[profile.default]
src = 'contracts'
out = 'artifacts'
libs = ['lib', '../../../lib', '../../../node_modules']
solc_version = '0.8.19'
optimizer_runs = 800
remappings = [
    "test/=test/"
]
fs_permissions = [
    { access = 'read', path = './test/data' },
    { access = 'read-write', path = './history.json' },
    { access = 'read-write', path = './metrics.json' }
]
gas_reports = ["Challenge"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config